# Copyright 1998-2019 Lawrence Livermore National Security, LLC and other
# HYPRE Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

###############################################################################
##  All configurable variables are defined in the file named Makefile.config.in
##  When Autoconf is run, it will create a file named Makefile.config which
##  will have all of the configurable variables replaced with their values.
###############################################################################



srcdir = .
top_srcdir = ..
prefix = /home/wh3248/workspaces/build_parflow/hypre
exec_prefix = ${prefix}



HYPRE_RELEASE_NAME    = hypre
HYPRE_RELEASE_VERSION = 2.17.0
HYPRE_RELEASE_DATE    = 2019/06/10
HYPRE_RELEASE_TIME    = 00:00:00
HYPRE_RELEASE_BUGS    = hypre-support@llnl.gov

HYPRE_SRC_TOP_DIR = /home/wh3248/workspaces/build_parflow/hypre/src
HYPRE_BUILD_DIR   = /home/wh3248/workspaces/build_parflow/hypre/src/hypre

HYPRE_INSTALL_DIR = /home/wh3248/workspaces/build_parflow/hypre
HYPRE_LIB_INSTALL = ${exec_prefix}/lib
HYPRE_INC_INSTALL = ${prefix}/include

HYPRE_LIB_SUFFIX = .a

.SUFFIXES:
.SUFFIXES: .o .f .c .C .cxx .cc .cu

.f.o:
	$(FC) $(FFLAGS) -c $< 
.c.o:
	$(CC) $(CFLAGS) -c $< 
.C.o:
	$(CXX) $(CXXFLAGS) -c $<
.cxx.o:
	$(CXX) $(CXXFLAGS) -c $<
.cc.o:
	$(CXX) $(CXXFLAGS) -c $<
#.cu.o:
#	$(CUCC) $(CUFLAGS) -c $<

FC       = mpif77
FFLAGS   = -O2 -g -O2 $(FC_COMPILE_FLAGS)

CC       = mpicc
CFLAGS   = -O2  -DHAVE_CONFIG_H $(C_COMPILE_FLAGS)

CXX      = mpic++
CXXFLAGS = -O2  -DHAVE_CONFIG_H $(CXX_COMPILE_FLAGS)

#CUCC     = 
#CUFLAGS  =  -DHAVE_CONFIG_H ${CU_COMPILE_FLAGS}

LINK_FC  = mpif77
LINK_CC  = mpicc
LINK_CXX = mpic++

BUILD_FC_SHARED     = 
BUILD_CC_SHARED     = 
BUILD_CXX_SHARED    = 
SHARED_COMPILE_FLAG = 
SHARED_BUILD_FLAG   = 
SHARED_SET_SONAME   = 
SHARED_OPTIONS      = 

BUILD_PYTHON = 0
PYTHON       = 

BUILD_JAVA = 0

AR     = ar -rcu
RANLIB = ranlib

LDFLAGS = 
LIBS    =    -lm    
FLIBS   = 

INCLUDES =    

##################################################################
##  LAPACK Library Flags 
##################################################################
LAPACKLIBS      = 
LAPACKLIBDIRS   = 

##################################################################
##  BLAS Library Flags 
##################################################################
BLASLIBS        = 
BLASLIBDIRS     = 

##################################################################
##  MPI options
##################################################################
MPIINCLUDE = 
MPILIBDIRS = 
MPILIBS    =  
MPIFLAGS   = 

##################################################################
##  CUDA options
##################################################################
HYPRE_NVCC_MAKEFILE = @HYPRE_NVCC_MAKEFILE@
HYPRE_CUDA_INCL = 
HYPRE_CUDA_LIBS = 

##################################################################
##  Caliper options
##################################################################
CALIPER_INCLUDE = 
CALIPER_LIBS    = 

##################################################################
##  Euclid, ParaSails, pilut options
##################################################################
HYPRE_DISTRIBUTED_LS_DIR = /home/wh3248/workspaces/build_parflow/hypre/src/distributed_ls
HYPRE_EUCLID_FILES       = /home/wh3248/workspaces/build_parflow/hypre/src/distributed_ls/Euclid/*.o
HYPRE_PARASAILS_FILES    = /home/wh3248/workspaces/build_parflow/hypre/src/distributed_ls/ParaSails/*.o
HYPRE_PILUT_FILES        = /home/wh3248/workspaces/build_parflow/hypre/src/distributed_ls/pilut/*.o

##################################################################
##  SuperLU options
##################################################################
SUPERLU_INCLUDE = 
SUPERLU_LIBS    = 

##################################################################
##  DsuperLU options
##################################################################
DSUPERLU_INCLUDE = 
DSUPERLU_LIBS    = 

##################################################################
##  FEI options
##################################################################
HYPRE_FEI_SRC_DIR       = 
HYPRE_FEI_BASE_DIR      = 
HYPRE_FEI_SUBDIRS       = 
HYPRE_FEI_HYPRE_FILES   = 
HYPRE_FEI_FEMLI_FILES   = 

##################################################################
##  RAJA options
##################################################################
HYPRE_RAJA_LIB_DIR      = 
HYPRE_RAJA_INCLUDE      = 
HYPRE_RAJA_LIB          = 

##################################################################
##  kokkos options
##################################################################
HYPRE_KOKKOS_LIB_DIR    = 
HYPRE_KOKKOS_INCLUDE    = 
HYPRE_KOKKOS_LIB        = 

